# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "46e3839f24818638319c72bab3ffb1fc"
name = "app-builder"
handle = "app-builder-25"
application_url = "https://stanford-witness-institute-bush.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "customers/create", "customers/update" ]
  uri = "/webhooks/customers/update"

  [[webhooks.subscriptions]]
  topics = [ "inventory_levels/update" ]
  uri = "/webhooks/inventory/update"

  [[webhooks.subscriptions]]
  topics = [ "orders/create", "orders/paid", "orders/updated" ]
  uri = "/webhooks/orders/update"

  [[webhooks.subscriptions]]
  topics = [ "products/create", "products/delete", "products/update" ]
  uri = "/webhooks/products/update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://stanford-witness-institute-bush.trycloudflare.com/auth/callback", "https://stanford-witness-institute-bush.trycloudflare.com/auth/shopify/callback", "https://stanford-witness-institute-bush.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
